export const ALL_DOCTORS_SUCCESS = 'ALL_DOCTORS_SUCCESS'
export const ALL_DOCTORS_FAIL = 'ALL_DOCTORS_FAIL'
export const DOCTOR_DETAILS_SUCCESS = 'DOCTOR_DETAILS_SUCCESS'
export const DOCTOR_DETAILS_FAIL = 'DOCTOR_DETAILS_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const REVIEW_AVAILABILITY_REQUEST = 'REVIEW_AVAILABILITY_REQUEST'
export const REVIEW_AVAILABILITY_SUCCESS = 'REVIEW_AVAILABILITY_SUCCESS'
export const REVIEW_AVAILABILITY_FAIL = 'REVIEW_AVAILABILITY_FAIL'

export const ADMIN_DOCTORS_REQUEST = 'ADMIN_DOCTORS_REQUEST'
export const ADMIN_DOCTORS_SUCCESS = 'ADMIN_DOCTORS_SUCCESS'
export const ADMIN_DOCTORS_FAIL = 'ADMIN_DOCTORS_FAIL'

export const DELETE_DOCTOR_REQUEST = 'DELETE_DOCTOR_REQUEST'
export const DELETE_DOCTOR_SUCCESS = 'DELETE_DOCTOR_SUCCESS'
export const DELETE_DOCTOR_RESET = 'DELETE_DOCTOR_RESET'
export const DELETE_DOCTOR_FAIL = 'DELETE_DOCTOR_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'


