export const ALL_DOCTORS_SUCCESS = 'ALL_DOCTORS_SUCCESS'
export const ALL_DOCTORS_FAIL = 'ALL_DOCTORS_FAIL'
export const DOCTOR_DETAILS_SUCCESS = 'DOCTOR_DETAILS_SUCCESS'
export const DOCTOR_DETAILS_FAIL = 'DOCTOR_DETAILS_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const REVIEW_AVAILABILITY_REQUEST = 'REVIEW_AVAILABILITY_REQUEST'
export const REVIEW_AVAILABILITY_SUCCESS = 'REVIEW_AVAILABILITY_SUCCESS'
export const REVIEW_AVAILABILITY_FAIL = 'REVIEW_AVAILABILITY_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'


