
export const CHECK_BOOKING_REQUEST = 'CHECK_BOOKING_REQUEST'
export const CHECK_BOOKING_SUCCESS = 'CHECK_BOOKING_SUCCESS'
export const CHECK_BOOKING_RESET = 'CHECK_BOOKING_RESET'
export const CHECK_BOOKING_FAIL = 'CHECK_BOOKING_FAIL'
export const BOOKED_TIMES_SUCCESS = 'BOOKED_TIMES_SUCCESS'
export const BOOKED_TIMES_FAIL = 'BOOKED_TIMES_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
