export const REGISTER_DOCTOR_REQUEST = 'REGISTER_DOCTOR_REQUEST'
export const REGISTER_DOCTOR_SUCCESS = 'REGISTER_DOCTOR_SUCCESS'
export const REGISTER_DOCTOR_FAIL = 'REGISTER_DOCTOR_FAIL'

export const LOAD_DOCTOR_REQUEST = 'LOAD_DOCTOR_REQUEST'
export const LOAD_DOCTOR_SUCCESS = 'LOAD_DOCTOR_SUCCESS'
export const LOAD_DOCTOR_FAIL = 'LOAD_DOCTOR_FAIL'

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
